#!/bin/bash

# while-menu-dialog: a menu driven system information program

DIALOG_CANCEL=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0

display_result() {
  dialog --title "$1" \
    --no-collapse \
    --msgbox "$result" 0 0
}

while true; do
  exec 3>&1
  selection=$(dialog \
    --backtitle "Dotfiles master v1.1" \
    --title "Menu" \
    --clear \
    --cancel-label "Exit" \
    --menu "Please select:" $HEIGHT $WIDTH 4 \
    "1" "Inspect" \
    "2" "Backup" \
    "3" "Install" \
    2>&1 1>&3)
  exit_status=$?
  exec 3>&-
  case $exit_status in
    $DIALOG_CANCEL)
      clear
      echo "Program terminated."
      exit
      ;;
    $DIALOG_ESC)
      clear
      echo "Program aborted." >&2
      exit 1
      ;;
  esac
  case $selection in
    1 )
      vim dotfiles
      ;;
    2 )
      mkdir $HOSTNAME
      cp ~/.bashrc ./$HOSTNAME
      cp ~/.conkyrc ./$HOSTNAME
      cp ~/.conkyrc1 ./$HOSTNAME
      cp ~/.gtkrc-2.0 ./$HOSTNAME
      cp ~/.xinitrc ./$HOSTNAME
      cp ~/.Xresources ./$HOSTNAME
      cp -r ~/.config/ ./$HOSTNAME
      ;;
    3 )
      cp ./$HOSTNAME/.bashrc ~/
      cp ./$HOSTNAME/.conkyrc ~/
      cp ./$HOSTNAME/.conkyrc1 ~/
      cp ./$HOSTNAME/.gtkrc-2.0 ~/
      cp ./$HOSTNAME/.xinitrc ~/
      cp ./$HOSTNAME/.Xresources ~/
      cp -r ./$HOSTNAME/.config/ ~/
      ;;
  esac
done
